#!/bin/sh

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

tmpdir=$(mktemp -d -t viclip.XXXXXX)
tmpfile=$tmpdir/clipboard
xclip -o -selection clipboard > "$tmpfile"
${VISUAL:-${EDITOR:-editor}} "$tmpfile"
xclip -i -selection clipboard < "$tmpfile"
rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
